new_checked_board=[
    [[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False]],
    [[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False]],
    [[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False]],
    [[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False]],
    [[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False]],
    [[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False]],
    [[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False]],
    [[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False],[False,False]]
]